### PR TITLE
add visualizations

### PR DESCRIPTION
**Pull request by ghost**
this pull request updates the visualizations in the website carousel per issue https://github.com/capstone-coal/capstone-coal.github.io/issues/14.

[preview the changes](http://www.teom.net/capstone-coal.github.io/) on my site.

### CODE REVIEW

**Comment by ghost** [comment]
@lewismc i have added descriptions to the `alt` and `title` image attributes, including attribution to address issue https://github.com/capstone-coal/pycoal/issues/56. i took the text from our second poster draft which uses the same images. the images are now more accessible to screen readers and the descriptions should be displayed when the user hovers the cursor over the image. i also updated the [preview](http://www.teom.net/capstone-coal.github.io/).

**Comment by lewismc** [comment]
Thanks @browtayl

**Review by lewismc — COMMENTED** [review]
Thanks

**Comment by ghost** [comment]
@lewismc want me to merge this?

**Comment by ghost** [comment]
@lewismc i'm going ahead to merge and close which i assume was the intention.

**Pull request merged**
