### PR TITLE
ISSUE-6 add jekyll blog

### PR DESCRIPTION
**Pull request by xiaomei7**
I added the jekyll blog and some re-styling due to the original header is not compatible with jekyll.

### CODE REVIEW

**Comment by lewismc** [comment]
Thanks @xiaomei7 please see the attached screenshot... it still doesn't look right. Can you please take another look?

screen shot 2017-02-23 at 5 20 52 pm 2

**Comment by xiaomei7** [comment]
@lewismc This is because I use Jekyll with GitHub pages as the backend; it would not render the site if the local computer does not have the Jekyll environment installed. So I always commit to another repository to do the updates in order to see what the website looks like. 

Thank you

**Comment by xiaomei7** [comment]
https://github.com/xiaomei7/capstone-coal-test.github.io

This is the branch I used due to the reason I didn't install Jekyll on my Mac either, so I have to commit to seeing the changes to the website every time.

There is a link to the website under the title.

**Comment by lewismc** [comment]
@xiaomei7 your remote repository master branch is 115 commits ahead and 32 commits behind remote origin master branch. I think you need to rebase master branch and then create the branch which is named after the issue e.g. **ISSUE-8**. This is explained in the [COAL Development HOWTO](https://github.com/capstone-coal/pycoal/wiki/PyCOAL-Development-Workflow).

Anyways, I build the site with Jekyll locally and it still looks as if there are a lot of presentation issues. For example, there is a large white strip at the top of index.html, the font on all of the text is not right, the blogs look very bare with no content. Ideally we want the blog entries showing on the main page with links to the individual pages.

Can you please have another go at overhauling the Website? Thank you

**Comment by xiaomei7** [comment]
@lewismc Sorry for that I'm not to be very clear, the branch I posted above is just for me to do some testing; it is unrelated to this master branch. I used another branch called "Update-Branch" under the Master branch here to create the pull request; I will change the name of the sub-branch.

I will start to do the styling immediately. You mentioned the font is not right, so what kind of font is required? Also, There is no blog posting, so the blog page only has entries I post for testing; did you mean the blog page should be on the main page of the site and delete the presentation video that is there right now?

**Comment by xiaomei7** [comment]
I have just found out I can't rename the branch unless I delete it and create a new one. Since this pull request is under this branch, I decide to leave it right now and create a new branch with the right name after I finish some styling and possibly a new pull request.

Thanks

**Comment by lewismc** [comment]
No problems @xiaomei7 it can be tricky sometimes. Lets try and get this resolved and move on to other more exciting things.
With regards to the font... your guess is hopefully better than mine. I am not very creative on front end code... so please just make your own decision. Nothing too fancy but something which you think looks nice. Thank you very much.

**Pull request closed without merging**
